#!/usr/bin/env python3
"""Test Google Drive integration."""

import os
import sys
from dotenv import load_dotenv

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.learning.google_drive_sync import GoogleDriveKnowledgeSync
from app.learning import UniversalLearningLogger, KnowledgeExtractor

load_dotenv()

DB_CONFIG = {
    'host': os.getenv('PGHOST', 'localhost'),
    'port': int(os.getenv('PGPORT', 5432)),
    'dbname': os.getenv('PGDATABASE', 'n8n_agent_memory'),
    'user': os.getenv('PGUSER', 'n8n_agent'),
    'password': os.getenv('PGPASSWORD', '')
}

def test_gdrive():
    """Test Google Drive integration."""
    print("="*70)
    print("GOOGLE DRIVE INTEGRATION - TEST")
    print("="*70)
    print()

    # Check if credentials exist
    creds_path = os.getenv('GOOGLE_DRIVE_CREDENTIALS_PATH', './google_drive_credentials.json')
    if not os.path.exists(creds_path):
        print(f"⚠️  Google Drive credentials not found at: {creds_path}")
        print()
        print("To set up Google Drive integration:")
        print("1. Follow docs/GOOGLE_DRIVE_INTEGRATION.md")
        print("2. Create service account and download credentials")
        print("3. Save as google_drive_credentials.json")
        print("4. Add GOOGLE_DRIVE_CREDENTIALS_PATH to .env")
        print()
        print("Skipping Google Drive test.")
        return False

    try:
        # Initialize components
        print("Initializing learning components...")
        logger_inst = UniversalLearningLogger(DB_CONFIG)
        extractor = KnowledgeExtractor(
            DB_CONFIG,
            os.getenv('LLM_BASE_URL', 'http://localhost:11434/v1'),
            os.getenv('GEMINI_API_KEY', '')
        )
        print("✓ Learning components initialized")
        print()

        # Initialize Google Drive sync
        print("1. Initializing Google Drive sync...")
        print("-" * 70)
        gdrive = GoogleDriveKnowledgeSync(
            credentials_path=creds_path,
            root_folder_name=os.getenv('GOOGLE_DRIVE_ROOT_FOLDER', 'Dell Boca Vista Knowledge'),
            learning_logger=logger_inst,
            knowledge_extractor=extractor
        )

        print("✓ Google Drive sync initialized!")
        print(f"✓ Root folder: {gdrive.root_folder_name}")
        print(f"✓ Folder structure: {len(gdrive.folder_structure)} folders created")
        print()

        # Test input sync
        print("2. Syncing Input folder...")
        print("-" * 70)
        stats = gdrive.sync_input_folder()
        print(f"✓ Sync complete:")
        print(f"  - Files found: {stats['files_found']}")
        print(f"  - Files new: {stats['files_new']}")
        print(f"  - Files updated: {stats['files_updated']}")
        print(f"  - Files processed: {stats['files_processed']}")
        print(f"  - Concepts extracted: {stats['concepts_extracted']}")
        print()

        # Test reflection upload
        print("3. Uploading test reflection...")
        print("-" * 70)
        test_reflection = f"""Daily Learning Reflection - Test
Generated: {gdrive._get_file_hash('test')[:8]}

This is a test reflection to verify Google Drive upload is working.

Today's Learning:
- Successfully integrated Google Drive with learning system
- Tested bidirectional sync
- Folder structure created automatically

System Status: ✓ Operational

---
Generated by Dell Boca Vista Boys - Ultimate Learning System
"""

        file_id = gdrive.upload_daily_reflection(test_reflection)
        if file_id:
            print(f"✓ Reflection uploaded! File ID: {file_id}")
        else:
            print("✗ Reflection upload failed")
        print()

        # Test concepts upload
        print("4. Uploading test concepts...")
        print("-" * 70)
        test_concepts = [
            {
                'name': 'Test Concept - Google Drive Integration',
                'description': 'Successfully integrated Google Drive for knowledge sharing',
                'confidence': 0.95,
                'domain': 'system_integration'
            }
        ]

        concepts_file_id = gdrive.upload_concepts_summary(test_concepts)
        if concepts_file_id:
            print(f"✓ Concepts uploaded! File ID: {concepts_file_id}")
        else:
            print("✗ Concepts upload failed")
        print()

        # Summary
        print("="*70)
        print("✓ GOOGLE DRIVE INTEGRATION TEST PASSED!")
        print("="*70)
        print()
        print("Next steps:")
        print(f"1. Go to Google Drive: https://drive.google.com")
        print(f"2. Open folder: '{gdrive.root_folder_name}'")
        print("3. Check Output/Daily Reflections/ for test reflection")
        print("4. Check Output/Learned Concepts/ for test concepts")
        print("5. Add a document to Input/ folder to test learning")
        print()
        print("Folder structure:")
        for name, folder_id in gdrive.folder_structure.items():
            print(f"  - {name}: {folder_id[:20]}...")
        print()

        return True

    except Exception as e:
        print(f"\n✗ TEST FAILED: {e}")
        import traceback
        traceback.print_exc()
        print()
        print("Troubleshooting:")
        print("1. Check credentials file exists and is valid")
        print("2. Ensure Google Drive API is enabled")
        print("3. Share folder with service account email")
        print("4. See docs/GOOGLE_DRIVE_INTEGRATION.md for full setup")
        return False

if __name__ == "__main__":
    success = test_gdrive()
    sys.exit(0 if success else 1)
